name: Build and Upload Debug APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build Debug APK (Optimized)
        run: ./gradlew assembleDebug --no-daemon --max-workers=2 --offline --quiet

      - name: Cache gdrive CLI
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/gdrive
          key: gdrive-${{ runner.os }}

      - name: Authenticate gdrive
        run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive_service.json

      - name: Upload APK to Google Drive
        run: gdrive upload --parent 12eO5gP49IbeDTD_1TexBqcMxrc-jNiZJ app/build/outputs/apk/debug/app-debug.apk
