name: Build and Upload Debug APK

on:
  push:
    branches:
      - master  # Change this to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Install gdrive CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O gdrive.tar.gz https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64
          chmod +x gdrive-linux-x64
          sudo mv gdrive-linux-x64 /usr/local/bin/gdrive

      - name: Authenticate gdrive
        run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive_service.json

      - name: Upload APK to Google Drive
        run: gdrive upload --parent 12eO5gP49IbeDTD_1TexBqcMxrc-jNiZJ app/build/outputs/apk/debug/app-debug.apk
